export const initialHotels = [
  {
    image:'https://clck.ru/RPGFp',
    starsNumber: '5',
    name:  'Hotel Blue Haven',
    description: 'Good hotel',
    adress: '1749 Wheeler Ridge  Delaware',
    guestNumber: '2 x Guests',
    roomNumber: '1 x Room',
    oldPrice: '10500',
    newPrice: '8500',
  },
  {
    image: 'https://clck.ru/RPG5n',
    starsNumber: '5',
    name: 'LUX* Belle Mare',
    description: 'Good hotel',
    adress: '1749 Wheeler Ridge  Delaware',
    guestNumber: '4 x Guests',
    roomNumber: '2 x Room',
    oldPrice: '8500',
    newPrice: '3000',
  },
  {
    image: 'https://clck.ru/RPGAb',
    starsNumber: '5',
    name: 'White Palace',
    description: 'Good hotel',
    adress: '1749 Wheeler Ridge  Delaware',
    guestNumber: '2 x Guests',
    roomNumber: '1 x Room',
    oldPrice: '10500',
    newPrice: '9500',
  },
  {
    image: 'https://clck.ru/RPGAb',
    starsNumber: '5',
    name: 'White Palace',
    description: 'Good hotel',
    adress: '1749 Wheeler Ridge  Delaware',
    guestNumber: '1 x Guests',
    roomNumber: '1 x Room',
    oldPrice: '12500',
    newPrice: '10500',
  },
  {
    image: 'https://clck.ru/RPGEZ',
    starsNumber: '5',
    name: 'Luxury Place',
    description: 'Good hotel',
    adress: '1749 Wheeler Ridge  Delaware',
    guestNumber: '2 x Guests',
    roomNumber: '1 x Room',
    oldPrice: '4500',
    newPrice: '2500',
  },
  {
    image: 'https://clck.ru/RPGFp',
    starsNumber: '5',
    name: 'Hotel Five Star',
    description: 'Good hotel',
    adress: '1749 Wheeler Ridge  Delaware',
    guestNumber: '2 x Guests',
    roomNumber: '1 x Room',
    oldPrice: '6500',
    newPrice: '3500',
  }
]